# source ~/.local/oss-cad/env.sh

export OSSCAD := $(HOME)/.local/oss-cad
export PATH := $(OSSCAD)/bin:$(PATH)

BUILD_DIR:=build
VERILATOR_OUT_DIR:=$(BUILD_DIR)/verilator
SBY_OUT_DIR:=$(BUILD_DIR)/formal

VERILATOR_OPTS_COMMON:=--Wall --timing --trace -cc -sv \
	-exe --binary --build -O3 \
	--Mdir $(VERILATOR_OUT_DIR) \
	--verilate-jobs $(nproc) --build-jobs $(nproc) \
	-Wno-TIMESCALEMOD

# Verilator lint options (matches veridian.yml configuration)
VERILATOR_LINT_OPTS:=--lint-only -sv --timing -Wall \
	-I./rtl -I./sim

# Waiver files for different contexts (generated by Verilator)
# Use 'make generate-waivers' to create these from current warnings
# Testbench waivers are per-subfolder: sim/*/module.vlt
# Formal waivers are per-subfolder: formal/*/module.vlt

# All RTL source files for linting
RTL_SOURCES:=$(wildcard rtl/*.sv)

#helper function to convert - targets to _ e.g. sim-tick-div -> sim_tick_div
dash-to-underscore = $(subst -,_,$1)

.SECONDEXPANSION:

# pattern rules to build individual test benches
.PHONY: sim-%
sim-%: $$(VERILATOR_OUT_DIR)/sim_$$(call dash-to-underscore,$$*)
	$(eval MODULE := $(call dash-to-underscore,$*))
	./$(VERILATOR_OUT_DIR)/sim_$(MODULE)

$(VERILATOR_OUT_DIR)/sim_%: sim/$$(call dash-to-underscore,$$*)/tb_$$(call dash-to-underscore,$$*).sv rtl/$$(call dash-to-underscore,$$*).sv
	$(eval MODULE := $(call dash-to-underscore,$*))
	@mkdir -p $(VERILATOR_OUT_DIR)
	$(eval TB_WAIVER_FILE := sim/$(MODULE)/$(MODULE).vlt)
	verilator $(VERILATOR_OPTS_COMMON) \
    $(if $(wildcard $(TB_WAIVER_FILE)),$(TB_WAIVER_FILE)) \
    --top-module tb_$(MODULE) sim/$(MODULE)/tb_$(MODULE).sv -Irtl \
    -o sim_$(MODULE)

# SBY formal verification targets
.PHONY: sby-%
sby-%: formal/$$(call dash-to-underscore,$$*)/$$(call dash-to-underscore,$$*).sby rtl/$$(call dash-to-underscore,$$*).sv
	$(eval MODULE := $(call dash-to-underscore,$*))
	@mkdir -p $(SBY_OUT_DIR)
	sby -f -d $(SBY_OUT_DIR)/$(MODULE) formal/$(MODULE)/$(MODULE).sby

# Lint targets using Verilator (matches veridian.yml config)
# Note: We don't lint RTL files standalone - they're linted via testbenches and formal
.PHONY: lint
lint: lint-tb lint-formal

.PHONY: lint-tb
lint-tb:
	@echo "Linting testbench files..."
	@find sim -mindepth 1 -maxdepth 1 -type d | while read dir; do \
		module=$$(basename $$dir); \
		tb_file=$$dir/tb_$$module.sv; \
		waiver=$$dir/$$module.vlt; \
		if [ -f "$$tb_file" ]; then \
			echo "  Checking $$tb_file"; \
			if [ -f "$$waiver" ]; then \
				echo "    Using waiver file: $$waiver"; \
			fi; \
			verilator $(VERILATOR_LINT_OPTS) \
				--top-module tb_$$module \
				$$([ -f "$$waiver" ] && echo "$$waiver") \
				$$tb_file $(RTL_SOURCES) || exit 1; \
		fi; \
	done
	@echo "✓ All testbench files passed lint checks"

.PHONY: lint-formal
lint-formal:
	@echo "Linting formal verification files..."
	@find formal -mindepth 1 -maxdepth 1 -type d | while read dir; do \
		module=$$(basename $$dir); \
		formal_file=$$dir/$${module}_formal_top.sv; \
		waiver=$$dir/$$module.vlt; \
		if [ -f "$$formal_file" ]; then \
			echo "  Checking $$formal_file"; \
			if [ -f "$$waiver" ]; then \
				echo "    Using waiver file: $$waiver"; \
			fi; \
			verilator $(VERILATOR_LINT_OPTS) \
				--top-module $${module}_formal_top \
				$$([ -f "$$waiver" ] && echo "$$waiver") \
				$$formal_file $(RTL_SOURCES) || exit 1; \
		fi; \
	done
	@echo "✓ All formal verification files passed lint checks"

.PHONY: lint-all
lint-all: lint-tb lint-formal

# Generate waiver files using Verilator's --waiver-output
.PHONY: generate-waivers
generate-waivers: generate-tb-waivers generate-formal-waivers

.PHONY: generate-tb-waivers
generate-tb-waivers:
	@echo "Generating testbench waiver files (one per subfolder)..."
	@find sim -mindepth 1 -maxdepth 1 -type d | while read dir; do \
		module=$$(basename $$dir); \
		tb_file=$$dir/tb_$$module.sv; \
		if [ -f "$$tb_file" ]; then \
			echo "  Processing $$tb_file..."; \
			verilator $(VERILATOR_LINT_OPTS) \
				--top-module tb_$$module \
				$$tb_file $(RTL_SOURCES) \
				--waiver-output $$dir/$$module.vlt 2>&1 || true; \
			if [ -f $$dir/$$module.vlt ]; then \
				echo "    ✓ Generated $$dir/$$module.vlt"; \
			fi; \
		fi; \
	done
	@echo "✓ Generated testbench waiver files"

.PHONY: generate-formal-waivers
generate-formal-waivers:
	@echo "Generating formal waiver files (one per subfolder)..."
	@find formal -mindepth 1 -maxdepth 1 -type d | while read dir; do \
		module=$$(basename $$dir); \
		formal_file=$$dir/$${module}_formal_top.sv; \
		if [ -f "$$formal_file" ]; then \
			echo "  Processing $$formal_file..."; \
			verilator $(VERILATOR_LINT_OPTS) \
				--top-module $${module}_formal_top \
				$$formal_file $(RTL_SOURCES) \
				--waiver-output $$dir/$$module.vlt 2>&1 || true; \
			if [ -f $$dir/$$module.vlt ]; then \
				echo "    ✓ Generated $$dir/$$module.vlt"; \
			fi; \
		fi; \
	done
	@echo "✓ Generated formal waiver files"

.PHONY: clean
clean:
	rm -rf $(BUILD_DIR)/*

.PHONY: clean-waivers
clean-waivers:
	@echo "Removing generated waiver files..."
	@find sim -mindepth 2 -name "*.vlt" -type f -delete
	@find formal -mindepth 2 -name "*.vlt" -type f -delete
	@echo "✓ Waiver files removed"

.PHONY: help
help:
	@echo "Available targets:"
	@echo ""
	@echo "Simulation:"
	@echo "  sim-<module>          - Simulate testbench (e.g., sim-tick-div)"
	@echo ""
	@echo "Formal Verification:"
	@echo "  sby-<module>          - Run formal verification (e.g., sby-tick-div)"
	@echo ""
	@echo "Linting:"
	@echo "  lint                  - Lint testbenches and formal (includes RTL via -I)"
	@echo "  lint-tb               - Lint testbench files (includes RTL)"
	@echo "  lint-formal           - Lint formal verification files (includes RTL)"
	@echo "  lint-all              - Lint testbench and formal files"
	@echo ""
	@echo "Waiver Management:"
	@echo "  generate-waivers        - Generate all waiver files from current warnings"
	@echo "  generate-tb-waivers     - Generate testbench waiver file (sim/tb.vlt)"
	@echo "  generate-formal-waivers - Generate formal waiver files (formal/*/module.vlt)"
	@echo "  clean-waivers           - Remove generated waiver files"
	@echo ""
	@echo "Build:"
	@echo "  all                   - Run all simulations and formal verification"
	@echo "  clean                 - Remove build artifacts"
	@echo ""
	@echo "Waiver Files (auto-generated by Verilator):"
	@echo "  sim/*/module.vlt         - Testbench waivers (one per subfolder)"
	@echo "  formal/*/module.vlt      - Formal waivers (one per subfolder)"
	@echo ""
	@echo "Note: RTL is linted via testbenches and formal using -I, not standalone"
	@echo ""
	@echo "Note: Verilator uses .vlt files with \`verilator_config directive."
	@echo "      These are NOT called .verilator_config!"

.PHONY: all
all: lint sim-tick-div sim-sync-2ff sim-i2c-od-pads sby-tick-div sby-sync-2ff
