# source ~/.local/oss-cad/env.sh

export OSSCAD := $(HOME)/.local/oss-cad
export PATH := $(OSSCAD)/bin:$(PATH)

BUILD_DIR:=build
VERILATOR_OUT_DIR:=$(BUILD_DIR)/verilator
SBY_OUT_DIR:=$(BUILD_DIR)/formal
LINT_DIR:=$(BUILD_DIR)/lint

# Stamp files for dependency tracking
LINT_STAMP:=$(LINT_DIR)/.stamp
LINT_DEPFILE:=$(LINT_DIR)/gen.d

VERILATOR_OPTS_COMMON:=--Wall --timing --trace-fst -cc -sv \
	-exe --binary --build -O3 \
	--Mdir $(VERILATOR_OUT_DIR) \
	--verilate-jobs $(nproc) --build-jobs $(nproc) \
	-Wno-TIMESCALEMOD

# Verilator lint options (matches veridian.yml configuration)
VERILATOR_LINT_OPTS:=--lint-only -sv --timing -Wall \
	-I./rtl -I./sim

# Waiver files for different contexts (generated by Verilator)
# Use 'make generate-waivers' to create these from current warnings
# Testbench waivers are per-subfolder: sim/*/module.vlt
# Formal waivers are per-subfolder: formal/*/module.vlt

# All RTL source files for linting
RTL_SOURCES:=$(wildcard rtl/*.sv)

#helper function to convert - targets to _ e.g. sim-tick-div -> sim_tick_div
dash-to-underscore = $(subst -,_,$1)

.SECONDEXPANSION:

# pattern rules to build individual test benches
.PHONY: sim-%
sim-%: $$(VERILATOR_OUT_DIR)/sim_$$(call dash-to-underscore,$$*)
	$(eval MODULE := $(call dash-to-underscore,$*))
	./$(VERILATOR_OUT_DIR)/sim_$(MODULE)

$(VERILATOR_OUT_DIR)/sim_%: sim/$$(call dash-to-underscore,$$*)/tb_$$(call dash-to-underscore,$$*).sv rtl/$$(call dash-to-underscore,$$*).sv
	$(eval MODULE := $(call dash-to-underscore,$*))
	@mkdir -p $(VERILATOR_OUT_DIR)
	$(eval TB_WAIVER_FILE := sim/$(MODULE)/$(MODULE).vlt)
	verilator $(VERILATOR_OPTS_COMMON) \
    $(if $(wildcard $(TB_WAIVER_FILE)),$(TB_WAIVER_FILE)) \
    --top-module tb_$(MODULE) sim/$(MODULE)/tb_$(MODULE).sv -Irtl \
    -o sim_$(MODULE)

# SBY formal verification targets
.PHONY: sby-%
sby-%: formal/$$(call dash-to-underscore,$$*)/$$(call dash-to-underscore,$$*).sby rtl/$$(call dash-to-underscore,$$*).sv
	$(eval MODULE := $(call dash-to-underscore,$*))
	@mkdir -p $(SBY_OUT_DIR)
	sby -f -d $(SBY_OUT_DIR)/$(MODULE) formal/$(MODULE)/$(MODULE).sby

# ============================================================================
# Linting with auto-generated filelists
# ============================================================================

# Discover all HDL sources for dependency tracking
RTL_SRCS := $(shell find rtl -type f \( -name '*.sv' -o -name '*.v' \) 2>/dev/null)
SIM_SRCS := $(shell find sim -type f \( -name '*.sv' -o -name '*.v' \) 2>/dev/null)
FORMAL_SRCS := $(shell find formal -type f \( -name '*.sv' -o -name '*.v' \) 2>/dev/null)
ALL_HDL_SRCS := $(RTL_SRCS) $(SIM_SRCS) $(FORMAL_SRCS)

# Generate lint filelists (using Python script)
$(LINT_STAMP): $(ALL_HDL_SRCS) tools/gen_lint_filelists.py lint_config.yml | $(LINT_DIR)
	./tools/gen_lint_filelists.py --build-dir $(BUILD_DIR) --stamp $(LINT_STAMP) --depfile $(LINT_DEPFILE)

$(LINT_DIR):
	mkdir -p $(LINT_DIR)

# Include dependency file if it exists (for make-based rebuilds)
-include $(LINT_DEPFILE)

.PHONY: lint-lists
lint-lists: $(LINT_STAMP)

.PHONY: lint
lint: $(LINT_STAMP)
	./tools/lint_verilator.py

# Waiver file management using Python script
# Waivers are stored per-module: sim/<module>/<module>.vlt, formal/<module>/<module>.vlt
.PHONY: generate-waivers
generate-waivers: $(LINT_STAMP)
	./tools/manage_waivers.py generate

.PHONY: list-waivers
list-waivers:
	./tools/manage_waivers.py list

.PHONY: clean
clean:
	rm -rf $(BUILD_DIR)/*

.PHONY: clean-waivers
clean-waivers:
	./tools/manage_waivers.py clean

.PHONY: help
help:
	@echo "Available targets:"
	@echo ""
	@echo "Simulation:"
	@echo "  sim-<module>          - Simulate testbench (e.g., sim-tick-div)"
	@echo ""
	@echo "Formal Verification:"
	@echo "  sby-<module>          - Run formal verification (e.g., sby-tick-div)"
	@echo ""
	@echo "Linting:"
	@echo "  lint                  - Lint all modules (testbenches + formal)"
	@echo "  lint-lists            - Generate lint filelists (auto-run by lint)"
	@echo ""
	@echo "Waiver Management:"
	@echo "  generate-waivers      - Generate/update all waiver files (preserves commented lines)"
	@echo "  list-waivers          - List all waiver files"
	@echo "  clean-waivers         - Remove all waiver files"
	@echo ""
	@echo "Build:"
	@echo "  all                   - Run all simulations and formal verification"
	@echo "  clean                 - Remove build artifacts"
	@echo ""
	@echo "Waiver Files (auto-generated by Verilator):"
	@echo "  sim/*/module.vlt         - Testbench waivers (one per subfolder)"
	@echo "  formal/*/module.vlt      - Formal waivers (one per subfolder)"
	@echo ""
	@echo "Notes:"
	@echo "  - Filelists are auto-generated from rtl/sim/formal directories"
	@echo "  - Waivers preserve commented lines from git base"
	@echo "  - Use './tools/manage_waivers.py --help' for more options"

.PHONY: all
all: sim-tick-div sim-sync-2ff sim-i2c-od-pads sim-i2c-bit-prim sby-tick-div sby-sync-2ff sby-i2c-bit-prim
